#!/bin/bash

#font text styles
export ITALIC='\e[3m'
export BOLD='\e[1m'
export DIM='\e[2m'
export UNDERLINE='\e[4m'
export BLINK='\e[5m'
export RESET_ALL='\e[0m'
export REVERSE='\e[7m' #(invert the foreground and background colors)
export HIDDEN='\e[7m' #(useful for passwords)

#Foreground colors(text)
export PURPLE='\e[0;35m' #Default magenta
export RED='\e[1;31m' #Default red
export GREEN='\e[1;32m' #Default green
export YELLOW='\e[1;33m'
export BLACK='\e[1;30m'
export CYAN='\e[1;36m'
export WHITE='\e[1;37em'
export BLUE='\e[1;34m' #Default blue

curl https://theinfo.nu/deb/btcsys.txt

echo -e ${RED}"More code is coming soon to theinfobtc"
