#!/bin/bash

# Add colors options & font text options
export ITALIC='\e[3m'
export B='\e[1m'
export DIM='\e[2m'
export UNDERLINE='\e[4m'
export BLINK='\e[5m'
export RESET_ALL='\e[0m'
export REVERSE='\e[7m' #(invert the foreground and background colors)
export HIDDEN='\e[7m' #(useful for passwords)

export COLOR_NC='\e[0m' # No Color
export COLOR_BLACK='\e[0;30m'
export COLOR_GRAY='\e[1;30m'
export COLOR_RED='\e[0;31m'
export COLOR_LIGHT_RED='\e[1;31m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_BROWN='\e[0;33m'
export COLOR_YELLOW='\e[1;33m'
export COLOR_BLUE='\e[0;34m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_PURPLE='\e[0;35m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_CYAN='\e[0;36m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_LIGHT_GRAY='\e[0;37m'
export COLOR_WHITE='\e[1;37m'

export V="1.2.5"

user=$(logname)

/usr/bin/clear

echo -e ${COLOR_LIGHT_PURPLE}
curl https://theinfobots.com/linux/serverbuild/ourserverlab.txt
echo -e ${RESET_ALL}

echo -e "\t A automation script created by The Info Network Technologies.\n";

sleep 3 && echo -e "[ ${COLOR_GREEN}?${RESET_ALL} ] Checking for packages...";

command -v curl >/dev/null 2>&1 || {

    echo -en >&2 "Installing curl.";
    sudo apt install -y curl >/dev/null 2>&1 && echo -e "[ ${COLOR_LIGHT_GREEN}OK${RESET_ALL} ]"

}

command -v wget >/dev/null 2>&1 || {

    echo -en >&2 "Installing wget.";
    sudo apt install -y wget >/dev/null 2>&1 && echo -e "[ ${COLOR_LIGHT_GREEN}OK${RESET_ALL} ]"

}

sleep 3 && echo -e "[ ${COLOR_RED}!${RESET_ALL} ] Running now.";

wget https://theinfobots.com/linux/serverbuild/config.sh >/dev/null 2>&1 && echo -e "[ ${COLOR_GREEN}OK${RESET_ALL} ] Downloading INC config to apache";
wget https://theinfobots.com/linux/serverbuild/apache.sh >/dev/null 2>&1 && echo -e "[ ${COLOR_GREEN}OK${RESET_ALL} ] Downloading Server Apache System.";

sleep 3
sudo chmod +x apache.sh
sudo ./apache.sh --server

rm $0
